version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  rails_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
  rails_app_db:
    image: postgres:12.12-alpine
    container_name: rails_app_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: ruby
      POSTGRES_PASSWORD: ruby
    ports:
      - 5432:5432
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - rails_app_db
  rails_app_test:
    image: rails-app_rails_app
    container_name: rails_app_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - rails_app_db